return {
	atm_breach = {
		DisplayName = "ATM Breach",
		RequiredTool = "SignalDisruptor",
		ConsumesTool = false,
		PayoutMin = 350,
		PayoutMax = 650,
		Wanted = 1,
		Cooldown = 75,
		SecureSeconds = 30,
		DispatchTitle = "ATM Robbery",
		DispatchDescription = "Electronic interference reported at a cash machine.",
		DispatchReward = 200,
	},
	house_burglary = {
		DisplayName = "Vacant-Home Burglary",
		RequiredTool = "LockpickKit",
		ConsumesTool = true,
		PayoutMin = 1200,
		PayoutMax = 2200,
		Wanted = 2,
		Cooldown = 120,
		SecureSeconds = 45,
		DispatchTitle = "Residential Burglary",
		DispatchDescription = "A vacant home alarm triggered near Pine Basin.",
		DispatchReward = 300,
	},
	retail_burglary = {
		DisplayName = "Retail Burglary",
		RequiredTool = "PryBar",
		ConsumesTool = false,
		PayoutMin = 500,
		PayoutMax = 900,
		Wanted = 1,
		Cooldown = 90,
		SecureSeconds = 35,
		DispatchTitle = "Retail Break-In",
		DispatchDescription = "A storefront reported a forced register breach.",
		DispatchReward = 225,
	},
	office_safe = {
		DisplayName = "Office Safe Robbery",
		RequiredTool = "PryBar",
		ConsumesTool = false,
		PayoutMin = 800,
		PayoutMax = 1400,
		Wanted = 2,
		Cooldown = 105,
		SecureSeconds = 40,
		DispatchTitle = "Commercial Safe Breach",
		DispatchDescription = "A back-office safe has been forced open.",
		DispatchReward = 260,
	},
	vehicle_theft = {
		DisplayName = "Vehicle Theft",
		RequiredTool = "PryBar",
		ConsumesTool = false,
		PayoutMin = 700,
		PayoutMax = 1200,
		Wanted = 2,
		Cooldown = 110,
		SecureSeconds = 50,
		DispatchTitle = "Vehicle Theft",
		DispatchDescription = "A stolen vehicle pinged near the industrial district.",
		DispatchReward = 275,
	},
}